<?php
/**
 * Busca Auto Completar
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Ziny
 * @package    BuscaAutoCompletar
 * @copyright  Copyright (c) 2015 Agência Ziny (www.agenciaziny.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Agência Ziny <dev@agenciaziny.com.br>
 */
$_resultado = $this->getSuggestProducts();
$_sugestoes = Mage::helper('catalogsearch')->getSuggestCollection();
?>
<ul class="_autobuscacompletar">
    <li class="_esconde"></li>
    <?php if ($this->enabledSuggest()): ?>
        <?php foreach ($_sugestoes as $_suggest): ?>
            <li class="_sugestoes">
                <span class="_sugestao"><?php echo $_suggest->getQueryText(); ?></span>
                <span class="_total"><?php echo $_suggest->getNumResults(); ?></span>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if ($results->count() && $this->enabledPreview()): ?>
        <?php foreach ($_resultado as $pro): ?>
            <li class="_resultado">
                <a href="<?php echo $pro->getProductUrl(); ?>">
                    <?php if ($this->isShowImage()): ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($pro, 'small_image')->resize($this->getImageWidth(), $this->getImageHeight()); ?>" />
                    <?php endif; ?>
                    <?php if ($this->isShowName()): ?>
                        <div class="_titulo"><?php echo $pro->getName(); ?></div>
                    <?php endif; ?>
                    <?php if ($this->isShowDescription()): ?>
                        <?php $descricao = substr($pro->getDescription(), 0, $this->getNumDescriptionChar()); ?>
                        <div class="_descricao"><?php strip_tags(substr($descricao, 0, strrpos($descricao, ' '))); ?>...</div>
                    <?php endif; ?>
                </a>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>